//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMumu_MidtermProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Comments = new HashSet<Comments>();
            this.Likes = new HashSet<Likes>();
            this.Products = new HashSet<Products>();
            this.ProjectEditPermissions = new HashSet<ProjectEditPermissions>();
            this.ProjectIDType = new HashSet<ProjectIDType>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public decimal Goal { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int MemberID { get; set; }
        public int RoleID { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<decimal> AccumulatedAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Likes> Likes { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectEditPermissions> ProjectEditPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectIDType> ProjectIDType { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
