//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnMumu_MidtermProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectEditPermissions
    {
        public int ProjectEditPermissionID { get; set; }
        public int ProjectID { get; set; }
        public int MemberID { get; set; }
        public int PermissionLevelID { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual PermissionLevels PermissionLevels { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
