//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMumu_MidtermProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ServiceMsg { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
