//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMumu_MidtermProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZecZecEntities : DbContext
    {
        public ZecZecEntities()
            : base("name=ZecZecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<LikeDetails> LikeDetails { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<MemberInterestProjectType> MemberInterestProjectType { get; set; }
        public virtual DbSet<MemberRoleGroup> MemberRoleGroup { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<PermissionLevels> PermissionLevels { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProjectEditPermissions> ProjectEditPermissions { get; set; }
        public virtual DbSet<ProjectIDType> ProjectIDType { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectTypes> ProjectTypes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ShipmentStatus> ShipmentStatus { get; set; }
        public virtual DbSet<SubComments> SubComments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
